# Generated by Django 4.2.6 on 2023-10-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=122)),
                ('email1', models.CharField(max_length=122)),
                ('phone1', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=12)),
                ('enrol', models.CharField(max_length=20)),
                ('add', models.TextField()),
                ('city', models.CharField(max_length=122)),
                ('pin', models.CharField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
