# Generated by Django 4.2.6 on 2023-10-06 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usname', models.CharField(max_length=122)),
                ('email2', models.CharField(max_length=122)),
                ('password1', models.CharField(max_length=122)),
            ],
        ),
    ]
