# Generated by Django 4.2.6 on 2023-10-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_usname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Password_Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usname1', models.CharField(max_length=122)),
                ('op', models.CharField(max_length=20)),
                ('np', models.CharField(max_length=20)),
            ],
        ),
    ]
